The throw keyword raises an ArgumentError if used to exit a thread
